### ISSUE TITLE
got "Segmentation fault (core dumped)" while testing.

### ISSUE THREAD

**Issue by kaixin-bai** [ikalevatykh/pybullet_rendering#1]
```python -m unittest discover tests -v```
got
```
pybullet build time: Feb  6 2020 17:15:24
test_fill_frame (tests.bingings.test_frame.FrameTest) ... ok
test_skip_frame (tests.bingings.test_frame.FrameTest) ... ok
test_box_primitive (tests.bingings.test_scene_graph.SceneGraphTest) ... terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```
```python -m pybullet_rendering.examples.panda3d_gui --multisamples 8```
got
```pybullet build time: Feb  6 2020 17:15:24
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
Segmentation fault (core dumped)
```
Could you please help me to find where is the problem? Thanks!

**Comment by ikalevatykh** [comment]
Hi @kaixin-bai , thank you for your feedback. A possible reason is that you are using not the same pybullet version with which you compile the code. Therefore, they are binary incompatible. I see the compilation date of the pybullet library: Feb 6 2020. Try to remove the pybullet (`pip uninstall pybullet`) and to reinstall it from the directory that you specified in the `--bullet_dir` parameter.

**Comment by ikalevatykh** [comment]
Hi @kaixin-bai, do you still have some issues?

**Comment by kaixin-bai** [comment]
hi @ikalevatykh , thanks for the reply. I didn't solve it yet, but the problem seems because of Panda3D, I find that someone else has the same problem(https://discourse.panda3d.org/t/segmentation-fault-core-dumped/23726).

**Comment by ikalevatykh** [comment]
Thanks for the information @kaixin-bai.

**Comment by chenw23** [comment]
@kaixin-bai Hi Kaixin, I have encountered the same problem. However, I found that on my machine, giving this command a lifted permission can fix this problem and I will be able to see the GUI window. Maybe you can give a try as well? 
`sudo -H python3 -m pybullet_rendering.examples.panda3d_gui --multisamples 8`
