### ISSUE TITLE
P3dRenderer doesn't support masks?

### ISSUE THREAD

**Issue by seann999** [ikalevatykh/pybullet_rendering#12]
Just to confirm, but looking into the code ([this line](https://github.com/ikalevatykh/pybullet_rendering/blob/9bef4b63e13c2b1e9117bc34df7439272bb1af38/pybullet_rendering/render/panda3d.py#L143) in particular) for P3dRenderer leads me to believe that it doesn't support masks (e.g. for segmentation). Is this correct?
If so, I guess I'll have to use a separate renderer to get the masks?

**Comment by ikalevatykh** [comment]
Hi @seann999 . Yes, P3dRenderer doesn't support masks rendering by default. You can extend it by adding second scene rendering pass with colors equal to masks values like [PyrRenderer does](https://github.com/ikalevatykh/pybullet_rendering/blob/9bef4b63e13c2b1e9117bc34df7439272bb1af38/pybullet_rendering/render/pyrender.py#L98). You can use `PyrRenderer` as well.
