### ISSUE TITLE
got error "ModuleNotFoundError: No module named 'pybullet_rendering.bindings'"

### ISSUE THREAD

**Issue by kaixin-bai** [ikalevatykh/pybullet_rendering#2]
got error "ModuleNotFoundError: No module named 'pybullet_rendering.bindings'" while import pybullet_rendering. Intall process followed readme and report no error.

**Comment by ikalevatykh** [comment]
Hi @kaixin-bai, I think you are calling a script from the local package folder. So it's enough just change the path, for example:
```bash
$ cd
$ python -m pybullet_rendering.examples.panda3d_gui --multisamples 2

**Comment by kaixin-bai** [comment]
Thanks! It works perfect!
