### ISSUE TITLE
pybullet_rendering.examples.performance report error for panda3d

### ISSUE THREAD

**Issue by kaixin-bai** [ikalevatykh/pybullet_rendering#5]
while testing `python -m pybullet_rendering.examples.performance` got warning `:display:x11display(error): BadAccess (attempt to access private resource denied)` for panda3d and the output image also seems not normal. 

```
pybullet build time: Jun 16 2020 12:09:08
Test tiny...
Test egl...
Loaded EGL 1.5 after reload.
GL_VENDOR=NVIDIA Corporation
GL_RENDERER=GeForce GTX 1070/PCIe/SSE2
GL_VERSION=4.6.0 NVIDIA 418.40.04
GL_SHADING_LANGUAGE_VERSION=4.60 NVIDIA
Version = 4.6.0 NVIDIA 418.40.04
Vendor = NVIDIA Corporation
Renderer = GeForce GTX 1070/PCIe/SSE2
ven = NVIDIA Corporation
ven = NVIDIA Corporation
Destroy EGL OpenGL window.
Test pyrender...
Test panda3d...
:display:x11display(error): BadAccess (attempt to access private resource denied)
:display:gsg:glgsg(error): Could not load program: created-shader (The profile is not supported.)
:display:x11display(error): BadAccess (attempt to access private resource denied)
:display:gsg:glgsg(error): GL error 0x502 : invalid operation
:display:gsg:glgsg(error): An OpenGL error has occurred.  Set gl-debug #t in your PRC file to display more information.
:display:x11display(error): BadAccess (attempt to access private resource denied)
Results:
tiny: 91.50 fps
egl: 337.91 fps
pyrender: 45.63 fps
panda3d: 503.28 fps
```

![color_egl](https://user-images.githubusercontent.com/38804949/85794121-604d0a00-b736-11ea-8411-ae39e415d506.png)
![color_panda3d](https://user-images.githubusercontent.com/38804949/85794122-60e5a080-b736-11ea-847d-e9807d044eae.png)
![color_pyrender](https://user-images.githubusercontent.com/38804949/85794124-617e3700-b736-11ea-9bfb-5962de3122de.png)
![color_tiny](https://user-images.githubusercontent.com/38804949/85794125-617e3700-b736-11ea-8145-1712651e6df0.png)

**Comment by kaixin-bai** [comment]
after i disable the other render engine, panda3d returns right data.

**Comment by juancamilog** [comment]
> after i disable the other render engine, panda3d returns right data.

What exactly do you mean by this? I'm getting the exact same problem.
