### ISSUE TITLE
Compilation error: invalid new-expression of abstract class type ‘RenderingInterface’

### ISSUE THREAD

**Issue by ManifoldFR** [ikalevatykh/pybullet_rendering#6]
Hi,

I am getting a compilation error due to unimplemented pure virtual member functions in `RenderingInterface`:

```
/home/manifold/Documents/pybullet_rendering/src/plugin/RenderingPlugin.cpp: In function ‘int initPlugin_RenderingPlugin(b3PluginContext*)’:
/home/manifold/Documents/pybullet_rendering/src/plugin/RenderingPlugin.cpp:35:42: error: invalid new-expression of abstract class type ‘RenderingInterface’
   35 |     auto render = new RenderingInterface();
      |                                          ^
In file included from /home/manifold/Documents/pybullet_rendering/src/plugin/RenderingPlugin.cpp:7:
/home/manifold/Documents/pybullet_rendering/src/plugin/RenderingInterface.h:18:7: note:   because the following virtual functions are pure within ‘RenderingInterface’:
   18 | class RenderingInterface : public UrdfRenderingInterface
      |       ^~~~~~~~~~~~~~~~~~
```

My system:
- Ubuntu 20.04.1 (up-to-date)
- Python 3.7.8 (conda)
- GCC 9.3.0
- pybind11 2.4.3
- Bullet3 latest (from Git, so PyBullet version `>=3.0.0`)

I've also tested compiling with Clang instead of GCC, but it made no difference.

**Comment by ikalevatykh** [comment]
Hi,

Rendering interface was changed in PyBullet recently without back-compatibility. I've updated it to conform the latest version. 

The new API supports deformables and heightfields. It seems this API still in active development, so I prefer wait while it stabilized before implement it in pybullet_rendering.

**Comment by ManifoldFR** [comment]
Great, thanks ! I'll keep an eye on things and eventually make PRs.
